-- Jalankan di Supabase Dashboard > SQL Editor.
CREATE TABLE IF NOT EXISTS public.tbl_kehadiran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nrp VARCHAR(20) NOT NULL,
  mata_kuliah VARCHAR(150) NOT NULL,
  catatan VARCHAR(500),
  latitude NUMERIC(10, 7) NOT NULL,
  longitude NUMERIC(10, 7) NOT NULL,
  foto_path TEXT NOT NULL,
  waktu_absen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  absen_tanggal DATE NOT NULL
    DEFAULT ((NOW() AT TIME ZONE 'Asia/Jakarta')::DATE),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_absen_per_hari UNIQUE (nrp, mata_kuliah, absen_tanggal)
);

CREATE INDEX IF NOT EXISTS idx_kehadiran_nrp
  ON public.tbl_kehadiran (nrp);

CREATE INDEX IF NOT EXISTS idx_kehadiran_waktu_absen
  ON public.tbl_kehadiran (waktu_absen DESC);

ALTER TABLE public.tbl_kehadiran ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT SELECT, INSERT ON TABLE public.tbl_kehadiran TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Foto selfie disimpan dalam bucket private "attendance-photos" di Supabase
-- Storage; buat bucket tersebut lewat Storage > New bucket.

-- Jika data masih berada di MySQL lokal, ekspor dan migrasikan data tabel
-- secara terpisah ke PostgreSQL sebelum memakai aplikasi cloud.
